### PR TITLE
[WIP] Make possible to collect skipped elements/bodyTexts/atrributes to list

### PR DESCRIPTION
**Pull request by WeaponMan**
Build on top of gradle pull request.
We have have customer at work and I must provide some log to show how many xml was skipped.
I am not sure if you accept this idea.
Please take look at the changes.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Really not sure about this. What's the aim of providing this skipping information to your customer? To clean up your xml feeds?

**Comment by WeaponMan** [comment]
It is instructions to build survey forms with complex logic.
They need this feedback for information what is broken with xml or skipped.
When something is skipped the user is not allowed to open the form.
I pick this library because is faster than XStream (currently used in app).
In Xtsream is MapperWrapper for this kind of stuff.

**Comment by sockeqwe** [comment]
isn't it enough to use `.exceptionOnUnreadXml(true)` and  react on the exception like sending this information to the server?

**Comment by WeaponMan** [comment]
No, because if user is in admin mode  only SnackBar will be shown with skipped/unsupported stuff and user can proceed to fill the survey forms.
They have survey form for selenium testing with elements (logic) that we currently don't support and there will be always something unsupported.
If exception on first missing thing will be thrown there will be no more selenium testing for supported stuff.
I hope this make sense.

**Comment by WeaponMan** [comment]
In this PR only messages almost same as exception messages are collected when supplied list for them is not null and `.exceptionOnUnreadXml(false)`

**Comment by sockeqwe** [comment]
Some thoughts:
1. Isn't it enough to catch the `XmlDataException` with `.exceptionOnUnreadXml(true)`. So if you have unread xml attributes (or whatever) a exception is thrown. Then its just a matter of displaying the error message in a Snackbar (if admin) or send it to the server (if user) and don't display it on the screen (or display a error message for the user). This follows clearly the "crash fast, crash early strategy". Also you can't be sure that any next selenium test has some kind of dependency to the part that is missing. So you basically gain no 100% trust in your tests, which is "almost the same as not having tests at all" if you cant trust your tests for 100%
2. I don't understand what the admin or user has to do in case that i.e. an xml element is not read. Doesnt the developer have to implement handling this xml element in you apps code?
3. I'm not sure how to implement this properly. For example, how would this work with Retrofit?
4. I would like to keep the API as clean and minimal as possible. This feature seems to be very specific to your own use case. Once accepting this API change, it is very hard to draw a baseline to decide which feature request should be added.
5. I might would implement this slightly different. Maybe adding a "error logger" as part of TikXmlConfig (configureable through builder) instead of adding an additional method parameter. There could be a "error logger" implementation that just writes to an ArrayList.
6. I have some ideas how to improve parsing speed in the future (maybe in TikXml 2.0 release) by supporting parsing one xml document with multiple threads (one thread only parses one part of the xml document). So threadsafety is important and must be taken into account while designing any new API in TikXml. That might break the order of events sent to an "error logger" and should be discussed beforehand. 
7. Overall I would prefer to add such a feature after a `1.0.0` release, maybe in `1.1.0`. Towards `1.0.0` I would like to focus on speed and correctnes. Then (after 1.0.0) on memory consumption and then on new features.

**Comment by WeaponMan** [comment]
1. Its testable selenium form has some stability but some unsupported things that are ignored in test suit for Android App. 
2. Normal user has to call to customer support and support will be solving this issue by creating it to our bug tracker (with info sended to server) or fix xml on their side. 
3. Good question
5. That was my first idea.
6. Order is not my concern

Ok, put this PR into Backlog issue.

**Comment by sockeqwe** [comment]
First of all, thank you for your hard work! Really appreciate it! 

I'm not saying that we can't add this feature in the future, but first I would like to focus on a `1.0.0` version without this feature, but I gladly put this feature into the backlog and let's discuss this feature after 1.0 release. See #72

**Pull request closed without merging**
