### PR TITLE
Default constructor fix 

### PR DESCRIPTION
**Pull request by WeaponMan**
I have today problem with error:
**Class X must provide an public empty (parameter-less) constructor**

when the class has valid empty constructor inherited from java.lang.Object.

Example:
```
@Xml
class AAction {
}

@Xml
class BAction {
}

@Xml(name = "event")
public class Event {
    @Path("action")
    @Element(typesByElement = {
     @ElementNameMatcher(name = "aaction", type = AAction.class),
            @ElementNameMatcher(name = "baction", type = BAction,class)
    })
    public Object action;
}
```

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks. Can you please also write a test for this here
https://github.com/Tickaroo/tikxml/tree/master/annotationprocessingtesting

Ondřej Kotora <notifications@github.com> schrieb am Sa., 3. Juni 2017,
22:31:

**Comment by sockeqwe** [comment]
Btw, which jdk do you use? I can't reproduce it on open jdk 1.8.51

Hannes Dorfmann <hannes.dorfmann@gmail.com> schrieb am Sa., 3. Juni 2017,
22:59:

**Comment by WeaponMan** [comment]
I have more complex object graph then this piece, but i can try to write complex test with obfuscated xml bindings.
I used oracle-jre 1.8.0_120 (win x64) compiled on java gradle project with apt plugin "net.ltgt.gradle:gradle-apt-plugin:0.10".

**Comment by WeaponMan** [comment]
Current master (commit 758d82d19810b2d36531d05410ab0e2ae575af83) will not compile this annotated classes ending with error above.

**Comment by sockeqwe** [comment]
Thanks, unfortunately I am on holidays and reviewing your code on mobile phone is a little bit cumbersome so i might review it in details on Wednesday.

Sorry for being nitpicking but I have to ask you to add one more test to this file:
https://github.com/Tickaroo/tikxml/blob/master/processor/src/test/java/com/tickaroo/tikxml/processor/scanning/DefaultAnnotationDetectorTest.kt
That just test that it compiles with empty constructor.

**Comment by WeaponMan** [comment]
I removed previous commit and added compilation test as you suggested.

**Comment by sockeqwe** [comment]
Ok, I will merge this right now, I'm just not sure if this will cause any major pain when merging your maven to gradle pull request #68 

Any thoughts?

**Comment by sockeqwe** [comment]
Thanks a lot for your work!

**Comment by WeaponMan** [comment]
I merged this yesterday and today into my other gradle branch with no conflicts.

**Comment by sockeqwe** [comment]
ok, thanks again! I have merged it to master branch and snapshot containing this fix will be auto deployed in a few minutes. `0.8.12-SNAPSHOT`

**Pull request merged**
