### PR TITLE
Annotation Processor Option for Android's ArrayMap

### LINKED ISSUE #37: Use ArrayMap instead of HashMap
Right now `HashMap<String, ChildElementBinder<T>>` or `HashMap<String, AttributeBinder<T>>`  is used in generated Code. This could be optimized for Android to use [ArrayMap](https://developer.android.com/reference/android/support/v4/util/package-summary.html)

We should add an Annotation Processor Option to turn this on / off in case that TikXml is in a java project

### PR DESCRIPTION
**Pull request by iNoles**
Fixed #37

### CODE REVIEW

**Comment by iNoles** [comment]
@sockeqwe What is your thought of this?

**Comment by sockeqwe** [comment]
Sorry, I completely forgot about this PR. Im very sorry!

How would you use this option at the end?

```gradle
kapt {
   arguments {
      arg ("tikxml.arrayMap", "true")
   }
}
```

I think we could make this even more generic by passing the full qualified class name of `Map` implementation that should be used. Something like this:

 ```gradle
kapt {
   arguments {
      arg ("tikxml.mapImpl", "android.support.v4.util.ArrayMap")
   }
}
``` 

Then we are pretty flexible with any kind of `Map` implementation the user wants to use, i.e.
```
arg ("tikxml.mapImpl", "androidx.collection.ArrayMap")
```

or

```
arg ("tikxml.mapImpl", "java.util.TreeMap")
```

The downside, however, is that `androidx.collection.ArrayMap` is actually not implementing `Map` interface (`android.support.v4.util.ArrayMap` does?!?!?)

**Comment by WeaponMan** [comment]
It does implement Map:
`public class ArrayMap<K, V> extends SimpleArrayMap<K, V> implements Map<K, V>`

**Comment by sockeqwe** [comment]
Yes, but `androidx.collection.ArrayMap` is not implementing Map see 
https://developer.android.com/reference/kotlin/androidx/collection/ArrayMap

**Comment by iNoles** [comment]
@sockeqwe "this implementation is a version of the platform's android.util.ArrayMap that can be used on older versions of the platform."

**Comment by sockeqwe** [comment]
Not sure if we need this. looks like a big `switch` rather than a `hashmap` has same / smilar performance characteristics ...

**Comment by iNoles** [comment]
@sockeqwe close this?

**Comment by sockeqwe** [comment]
No I will review it on Monday and most likely merge it. Sorry for the long pause and thanks again for your hard work.

**Pull request merged**
